PKCS1RSA
    DEFINITIONS EXPLICIT TAGS ::=
BEGIN

RSAPublicKey ::= SEQUENCE {
    modulus           INTEGER,
    publicExponent    INTEGER
}

RSAPrivateKey ::= SEQUENCE {
    version           INTEGER,
    modulus           INTEGER,
    publicExponent    INTEGER,
    privateExponent   INTEGER,
    prime1            INTEGER,
    prime2            INTEGER,
    exponent1         INTEGER,
    exponent2         INTEGER,
    coefficient       INTEGER,
    otherPrimeInfos   OtherPrimeInfos OPTIONAL
}

OtherPrimeInfos ::= SEQUENCE OF OtherPrimeInfo

OtherPrimeInfo ::= SEQUENCE {
    prime        INTEGER,
    exponent     INTEGER,
    coefficient  INTEGER
}

END
