#include <common.h>
#include <rand.h>
#include <pem.h>
#include <base64.h>
#include <des.h>
#include <textutil.h>
#include <libft/bytes.h>

static const char	*PEM_PROC = "Proc-Type: 4,ENCRYPTED\n";
static const char	*DEK_INFO = "DEK-Info: DES-CBC,";

static int	__base64_encode(t_ostring *content, t_ostring *pemenc);

// Encrypted PEM format:
//
// -----BEGIN X-----
// Proc-Type: 4,ENCRYPTED
// DEK-Info: CIPHER,PEMIV
// [ ... BASE64 ENCODING ... ]
// -----END X-----
//
// OpenSSL uses a non-standard ecryption format for PEM encoding.
// PEM initial vector (PEMIV) is used as CIPHER salt and
// CIPHER initial vector. Thus, CIPHER key is generated using PEMIV
// as a salt. Generated key and PEMIV (aka initial vector) are then
// passed to CIPHER. Initial vector generated by PBKDF function
// is ignored.

int	pem_encode(t_ostring *content, t_pem **pem, const char *type, const char *pass)
{
	t_ostring	pemenc, cipher;
	t_des		*des;
	uint8_t		key[8], vect[8];
	char		*vecthex;
	int			ret;

	if (NULL == pem || NULL == content) {
		PEM_LOG(ERROR, INVALID_INPUT_ERROR);
		return (SSL_ERR);
	}

	ret = SSL_ERR;
	
	*pem = NULL;
	ft_ostr_init(&pemenc);
	ft_ostr_init(&cipher);

	if (NULL == pass) {
		if (SSL_OK != __base64_encode(content, &pemenc)) {
			PEM_LOG(ERROR, "base64 encode failed");
			goto label_exit;
		}
	}
	else {
		if ((SSL_OK != rand_useed((uint64_t *)vect, 8))) {
			PEM_LOG(ERROR, "rand useed failed");
			goto label_exit;
		}
		if (SSL_OK != rand_pbkdf2(key, vect, NULL, pass)) {
			PEM_LOG(ERROR, "rand pbkdf2 failed");
			goto label_exit;
		}
		des = des_init(key, NULL, vect);

		if (SSL_OK != des_cbc_encrypt(des, content, &cipher, pass)) {
			PEM_LOG(ERROR, "des cbc encrypt failed");
			goto label_exit;
		}
		ft_bzero(key, sizeof(key));

		ft_ostr_append(&pemenc, (char *)PEM_PROC, ft_strlen(PEM_PROC));
		ft_ostr_append(&pemenc, (char *)DEK_INFO, ft_strlen(DEK_INFO));

		vecthex = ft_bytes_to_hex(vect, sizeof(vect));
		ft_ostr_append(&pemenc, vecthex, ft_strlen(vecthex));
		SSL_FREE(vecthex);

		ft_ostr_append(&pemenc, "\n\n", 2);
		
		if (SSL_OK != __base64_encode(&cipher, &pemenc)) {
			PEM_LOG(ERROR, "base64 encode failed");
			goto label_exit;
		}
	}
	pem_encap(pem, type, pemenc.content, pemenc.size);

	ret = SSL_OK;

label_exit:
	ft_ostr_clear(&pemenc);
	ft_ostr_clear(&cipher);
	return (ret);
}

static int	__base64_encode(t_ostring *content, t_ostring *pemenc)
{
	char	*b64;
	size_t	b64size;

	b64 = NULL;
	b64size = 0;

	if (SSL_OK != base64_encode((char *)(content->content), content->size, &b64, &b64size)) {
		PEM_LOG(ERROR, UNSPECIFIED_ERROR);
		return (SSL_ERR);
	}
	textutil_insert_delim(&b64, &b64size, '\n', 64);
	ft_ostr_append(pemenc, b64, b64size);
	SSL_FREE(b64);

	return (SSL_OK);
}
