#include <common.h>
#include <rand.h>
#include <pem.h>
#include <base64.h>
#include <des.h>
#include <textutil.h>
#include <libft/bytes.h>

static int	__base64_encode(t_ostring *content, t_ostring *pemenc);

// Encrypted PEM format:
//
// -----BEGIN X-----
// Proc-Type: 4,ENCRYPTED
// DEK-Info: CIPHER,PEMIV
// [ ... BASE64 ENCODING ... ]
// -----END X-----
//
// OpenSSL uses a non-standard ecryption format for PEM encoding.
// PEM initial vector (PEMIV) is used as CIPHER salt and
// CIPHER initial vector. Thus, CIPHER key is generated using PEMIV
// as a salt. Generated key and PEMIV (aka initial vector) are then
// passed to CIPHER. Initial vector generated by PBKDF function
// is ignored.

int	pem_encode(t_pem *pem, t_ostring *data, t_ostring *enc, const char *label, const char *pass)
{
	t_ostring	pemenc, cipher;
	t_des		*des;
	char		buf[1024], *vecthex;
	int			ret;

	if (NULL == pem || NULL == data || NULL == enc) {
		PEM_LOG(ERROR, INVALID_INPUT_ERROR);
		return (SSL_ERR);
	}

	ret = SSL_ERR;
	
	ft_ostr_init(&pemenc);
	ft_ostr_init(&cipher);

	ft_snprintf(buf, sizeof(buf), "%s%s%s", "-----BEGIN ", label, "-----\n");
	ft_ostr_append(&pemenc, buf, ft_strlen(buf));

	if (pem->proc == PEM_PROC_TYPE_NONE) {
		if (SSL_OK != __base64_encode(data, &pemenc)) {
			PEM_LOG(ERROR, "base64 encode failed");
			goto label_exit;
		}
	}
	else {
		if (pem->proc == PEM_PROC_TYPE_ENCRYPTED) {
			ft_strcpy(buf, "Proc-Type: 4,ENCRYPTED\n");
			ft_ostr_append(&pemenc, buf, ft_strlen(buf));
		} else {
			PEM_LOG(ERROR, "invalid pem proc type: %d", pem->proc);
			goto label_exit;
		}

		if ((SSL_OK != rand_useed((uint64_t *)pem->iv, 8))) {
			PEM_LOG(ERROR, "rand useed failed");
			goto label_exit;
		}
		if (SSL_OK != rand_openssl_kdf((unsigned char *)pem->key, (unsigned char *)pem->iv, NULL, pass)) {
			PEM_LOG(ERROR, "rand pbkdf2 failed");
			goto label_exit;
		}
		des = des_init((unsigned char *)pem->key, NULL, (unsigned char *)pem->iv);

		if (SSL_OK != des_cbc_encrypt(des, data, &cipher, pass)) {
			PEM_LOG(ERROR, "des cbc encrypt failed");
			goto label_exit;
		}

		if (pem->cipher == PEM_CIPHER_DES_CBC) {
			vecthex = ft_bytes_to_hex(pem->iv, sizeof(pem->iv));
			ft_snprintf(buf, sizeof(buf), "DEK-Info: DES-CBC,%s\n\n", vecthex);
			ft_ostr_append(&pemenc, buf, ft_strlen(buf));
			SSL_FREE(vecthex);
		} else {
			PEM_LOG(ERROR, "unsupported pem cipher type: %d", pem->cipher);
			goto label_exit;
		}

		if (SSL_OK != __base64_encode(&cipher, &pemenc)) {
			PEM_LOG(ERROR, "base64 encode failed");
			goto label_exit;
		}
	}

	ft_snprintf(buf, sizeof(buf), "%s%s%s", "-----END ", label, "-----\n");
	ft_ostr_append(&pemenc, buf, ft_strlen(buf));

	ret = SSL_OK;

label_exit:
	ft_ostr_clear(&pemenc);
	ft_ostr_clear(&cipher);
	return (ret);
}

static int	__base64_encode(t_ostring *content, t_ostring *pemenc)
{
	t_ostring	b64, b64_with_delim;
	int			ret;

	ft_ostr_init(&b64);
	ft_ostr_init(&b64_with_delim);
	ret = SSL_ERR;

	if (SSL_OK != base64_encode(content->content, content->size, &b64.content, &b64.size)) {
		PEM_LOG(ERROR, UNSPECIFIED_ERROR);
		return (SSL_ERR);
	}
	if (SSL_OK != textutil_insert_delim((char *)b64.content, b64.size, (char **)&b64_with_delim.content, &b64_with_delim.size, '\n', 64)) {
		PEM_LOG(ERROR, "base64 format failed");
		ret = SSL_ERR;
	} else {
		ft_ostr_append(pemenc, b64_with_delim.content, b64_with_delim.size);
		ret = SSL_OK;
	}
	ft_ostr_clear(&b64);
	ft_ostr_clear(&b64_with_delim);

	return (ret);
}
